<?php
/**
 * @author    ShareThis
 * @copyright Copyright (c) 2022 ShareThis (https://sharethis.com)
 * @license   https://www.gnu.org/licenses/gpl-3.0.html
 * @package   ShareThis_ShareButtons
 *
 * @var ShareButtons $block
 */

use ShareThis\ShareButtons\Block\ShareButtons;

?>
<?php if (false === $block->isEnabled()): ?>
    <style>.st-sticky-share-buttons{ display: none !important; }</style>
<?php endif; ?>
