version: '3.0'
services:
  web:
    container_name: st_magento
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes: # TODO: Move ./ShareThis/ShareButtons/ items to root (if possible).
      - ./ShareThis:/var/www/html/app/code/ShareThis/
  db:
    container_name: st_mysql
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    container_name: st_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data: