version: '3.0'
services:
  web:
    container_name: st_magento
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - ./Block:/var/www/html/app/code/ShareThis/ShareButtons/Block
      - ./etc:/var/www/html/app/code/ShareThis/ShareButtons/etc
      - ./Helper:/var/www/html/app/code/ShareThis/ShareButtons/Helper
      - ./Model:/var/www/html/app/code/ShareThis/ShareButtons/Model
      - ./Plugin:/var/www/html/app/code/ShareThis/ShareButtons/Plugin
      - ./Service:/var/www/html/app/code/ShareThis/ShareButtons/Service
      - ./view:/var/www/html/app/code/ShareThis/ShareButtons/view
      - ./composer.json:/var/www/html/app/code/ShareThis/ShareButtons/composer.json
      - ./composer.lock:/var/www/html/app/code/ShareThis/ShareButtons/composer.lock
      - ./registration.php:/var/www/html/app/code/ShareThis/ShareButtons/registration.php
  db:
    container_name: st_mysql
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env

  phpmyadmin:
    container_name: st_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data: